dubbo:
  config:
    multiple: true
  # 配置服务信息
  application:
    name: order-consumer
    # 禁用QOS同一台机器可能会有端口冲突现象
    qos-enable: false
    qos-accept-foreign-ip: false
  # 配置注册中心
  registries:
    order:
      address: nacos://172.16.2.151:8848
    other:
      address: nacos://172.16.1.156:8848
    goods:
      address: nacos://47.115.162.144:8847
  # 设置协议-协议由提供方指定消费方被动接受
  protocol:
    name: dubbo
    port: 28091 #20880
  # 设置超时时间
  consumer:
    timeout: 4000
    check: false
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialization-mode: always
    name: oomall_order
    url: jdbc:mysql://172.16.2.151:3306/oomall_order?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: ooad109mysql #ooad109mysql #alex20000211 #ooad109mysql #alex20000211 #ooad109mysql
    #schema: classpath:order-schema.sql
    #data: classpath:order-data.sql
    druid:
      #初始化时建立物理连接的个数
      initial-size: 3
      #最小连接池数量
      min-idle: 3
      #最大连接池数量
      max-active: 100
      #获取连接时最大等待时间
      max-wait: 60000
      filter:
        stat:
          #是否开启慢sql查询监控
          log-slow-sql: true
          #慢SQL执行时间
          slow-sql-millis: 100
      validation-query: select 1
    sql-script-encoding: UTF-8

public-test:
  managementgate: 47.110.147.122:18088 #47.110.147.122:18089 #localhost:8089 #47.110.147.122:18089
  mallgate: 47.110.147.122:18088 #47.110.147.122:18089 #localhost:8089 #47.110.147.122:18089
server:
  port: 8089