
pagehelper:
  helper-dialect: mysql

dubbo:
  application:
    name: dubbo-goods
  scan:
    base-packages: cn.edu.xmu.goods.service
  registry:
    address: nacos://localhost:8848 #nacos://47.115.162.144:8847
  protocol:
    name: dubbo
    port: 28091

#dubbo:
#  # 配置服务信息
#  application:
#    name: dubbo-goods
#    # 禁用QOS同一台机器可能会有端口冲突现象
#    qos-enable: false
#    qos-accept-foreign-ip: false
#  # 配置注册中心
#  registry:
#    address: nacos://47.115.162.144:8847
#  # 设置协议-协议由提供方指定消费方被动接受
#  protocol:
#    name: dubbo
#    port: 20880
#  # 设置超时时间
#  consumer:
#    timeout: 4000
#    check: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialization-mode: always
    name: oomall_order
    url: jdbc:mysql://localhost:3306/oomall_order?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: alex20000211
    schema: classpath:order-schema.sql
    data: classpath:order-data.sql
    druid:
      #初始化时建立物理连接的个数
      initial-size: 3
      #最小连接池数量
      min-idle: 3
      #最大连接池数量
      max-active: 100
      #获取连接时最大等待时间
      max-wait: 60000
      filter:
        stat:
          #是否开启慢sql查询监控
          log-slow-sql: true
          #慢SQL执行时间
          slow-sql-millis: 100
      validation-query: select 1
    sql-script-encoding: UTF-8
public-test:
  managementgate: localhost:8080
  mallgate: localhost:8080
server:
  port: 8080